### PR TITLE
[FIX] No suicide , Repo has no branch_id

### PR DESCRIPTION
**Pull request by nseinlet**
@mart-e 
do not kill the process after for example a cold reboot
if the process id is 0
or the process id is the runbot itself

### CODE REVIEW

**Comment by mart-e** [comment]
How could you get `build.pid==os.getpid()` ? I agree for the `if build.pid:` but I don't see how it happens for the rest.

**Comment by nseinlet** [comment]
@mart-e : FIX Repo has no branch_id

**Comment by llacroix** [comment]
How is this PR not yet merged....?

**Comment by moylop260** [comment]
👍 
Why this PR is not merged?
Can we help to merge it? (Maybe adding test or another thing)

**Pull request closed without merging**
