### PR TITLE
[FIX] runbot: smarter fallback on '-' splitting

### PR DESCRIPTION
**Pull request by dmo-odoo**
We used to split on the first '-' when fallbacking
to name guessing to find the closest branch. It
works pretty well for 7.0- and 8.0- branches, but
issues start to arise with saas-6- branches.

This solution is smarter. It first tries to look
for a saas- prefix and stops at the next '-'. If
it doesn't find one, it then stops at the first
'-' character. If no such character is found, the
whole branch name is returned, exactly as before.

### CODE REVIEW

**Comment by dmo-odoo** [comment]
Didn't try it on actual runbot, though, only played with fake branch names in python shell.

**Comment by KangOl** [comment]
I don't like hardcoding `saas` as a special case.

**Comment by dmo-odoo** [comment]
I understand. The first solution I wanted to do was to stop at first '-', try a git branch --list name, if it didn't return a matching branch, try with the next '-' and so on. I didn't do it because I was not sure how to do it since it needs to check for matching branches only in the other repo, not in the one of the current branch.

**Comment by dmo-odoo** [comment]
We found a better way: https://github.com/odoo/odoo-extra/commit/7163963abb6d0317ad1838067540ac257f299d47

**Pull request closed without merging**
